server: 
  port: 9600 
  
spring:
  application:
    name:  microservicecloud_config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NickLaughing/springcloud_config.git #GitHub上面的git仓库名字
 

